version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - ingress
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
        
networks:
 ingress:
  driver: overlay
  attachable: true

volumes:
    data: 
    letsencrypt: 

  
